### ISSUE TITLE
Построение графа общественного транспорта с использованием osmnx

### ISSUE THREAD

**Issue by MVjimboUniversity** [MVjimboUniversity/Urban-Public-Transport-Analysis-Service#12]
- [x] Просмотреть #4 
- [x] Построить граф, используя osmnx

**Comment by SergiusMagnus** [comment]
Исследование проведено. Результаты в [https://github.com/MVjimboUniversity/Urban-Public-Transport-Analysis-Service/blob/research_graph_creation/research/PublicTransportGraph.ipynb](url)
