### ISSUE TITLE
Перенос проекта

### ISSUE THREAD

**Issue by sevryukov** [MVjimboUniversity/Urban-Public-Transport-Analysis-Service#120]
@MVjimboUniversity @MVjimbo 

Владимир, здравствуйте. Как Ваши дела?

Центр информационных технологий и инженерных компетенций СПбГУ (ЦИТИК, ИТ Клиника) осуществляет консолидацию проектов, выполняемых в рамках учебной практики и смежных инициатив.
Для переноса репозитория в организацию на github, необходимо:

1. Быть владельцем репозитория (его создателем)
2. Ознакомиться с инструкцией: https://docs.github.com/ru/repositories/creating-and-managing-repositories/transferring-a-repository
3. По инструкции осуществить перенос репозитория в организацию: https://github.com/citec-spbu

После переноса репозитория доступ к нему, история и вся статистика сохраняются, что может использоваться участниками для демонстрации своего опыта. При этом меняется ссылка на репозиторий, но с прежних ссылок выполняется автоматический редирект на новые.
 
При возникновении вопросов пишите сюда или мне на почту.

**Comment by MVjimboUniversity** [comment]
Добрый вечер. Репозиторий в организацию перенес.

**Comment by sevryukov** [comment]
Отлично, спасибо!
