### ISSUE TITLE
Проверить корректность получаемых данных при работе с оригинальной библиотекой osmnx 

### ISSUE THREAD

**Issue by HikkMind** [MVjimboUniversity/Urban-Public-Transport-Analysis-Service#132]
После перехода на оригинальную библиотеку osmnx версии 1.9.4 и построения графа с помощью неё, необходимо проверить полученных данные на соответствие действительности

**Comment by rozotto** [comment]
Проверив корректность данных был сделан вывод о том, что в больших городах информация об остановках и связах между ними верна. Рассматривая регионы, были замечены следующие проблемы:
1. Отсутствие n-ого количества маршрутов в городе.
2. Наличие лишь связей, но не вершин графа (остановок).
3. Изолированные вершины графа, то есть остановки без связей.
