### ISSUE TITLE
Подбор комбинаций тэгов для получения необходимого вида транспорта

### ISSUE THREAD

**Issue by HikkMind** [MVjimboUniversity/Urban-Public-Transport-Analysis-Service#137]
Нужно определить с помощью каких флагов, передаваемых стандартным функциям `osmnx`, можно получить информацию о нужном виде транспорта и какую именно информацию

**Comment by HikkMind** [comment]
Для получения информации о всем общественном транспорте в городе можно использовать следующую конструкцию:
```
tags = {'public_transport': True}
fet = ox.features_from_place(city, tags=tags)
```
В этом случае `fet` будет объектом типа GeoDataFrame

**Comment by rozotto** [comment]
Принял в работу

**Comment by HikkMind** [comment]
С помощью стандартных функций библиотеки `osmnx` не удалось получить всю нужную информацию в нужном формате. Принято решение использовать в этих целях Overpass-API
