### ISSUE TITLE
Получить информацию о маршрутах транспорта

### ISSUE THREAD

**Issue by HikkMind** [MVjimboUniversity/Urban-Public-Transport-Analysis-Service#138]
С помощью функции `features_from_place` можно получить информацию об узлах (остановках) общественного транспорта. Необходимо найти способ получить связи между ними для дальнейшего построения графа

**Comment by HikkMind** [comment]
Удалось получить запрос, позволяющий получать связи в формате json
```
overpass_query = *текст запроса*
routes = ox._overpass._overpass_request(data={"data": overpass_query})   #json string
```
В `routes` содержится информация об отношении (название маршрута), список остановок и их ролей и координаты вершин ломаной, представляющей линию движения транспорта

**Comment by gekkkl** [comment]
Принял в работу

**Comment by HikkMind** [comment]
С помощью запроса к Overpass-API удалось получить информацию об отношениях по имени города. Информация содержит название маршрута и списки остановок маршрута. Дополнительно получаем координаты ломаной линии, по которой проходит маршрут на карте

**Comment by HikkMind** [comment]
Получилось представить данную информацию в виде датафрейма в виде osmid отношение и соответствующий список остановок (в виде osmid)

**Comment by HikkMind** [comment]
Через Overpass-API получили дополнительную информацию о маршруте как списке отрезков дорог. Они содержат как информацию о самих отрезках, так и о примыкающих к ним узлам
