### ISSUE TITLE
Добавить ноутбуки для составления графа

### ISSUE THREAD

**Issue by HikkMind** [MVjimboUniversity/Urban-Public-Transport-Analysis-Service#140]
Нужно добавить ноутбуки, в которых описан способ получения графа с использованием оригинальной библиотеки osmnx

**Comment by gekkkl** [comment]
Добавлен ноутбук по работе с стандартными функциями osmnx и работой с графом (добавление информации в граф)

**Comment by HikkMind** [comment]
Ноутбуки добавлены в папку `research`. В дальнейшем будут дополняться в соответствии с новым функционалом. Для этого будут созданы отдельные issue
