### ISSUE TITLE
Проверить порядок следования остановок и отрезков маршрута

### ISSUE THREAD

**Issue by HikkMind** [MVjimboUniversity/Urban-Public-Transport-Analysis-Service#144]
Если использовать Overpass-API для получения информации об отношениях, то остановки и отрезки маршрута (части дорог на карте) представляются в виде списков. Необходимо проверить соответствие их порядка порядку следования маршрута

**Comment by rozotto** [comment]
Порядок следования остановок и связей между ними верный. Однако есть отличия в получаемой информации: в некоторых городах отсутствует поле "role": "stop".
