### ISSUE TITLE
Добавить представление нескольких схожих вершин в качестве одной

### ISSUE THREAD

**Issue by HikkMind** [MVjimboUniversity/Urban-Public-Transport-Analysis-Service#151]
Одинаковые остановки, которые соответствуют разным направлениям движения транспорта отмечены как совершенно разные, хотя в действительности в большинстве случаев имеют одинаковое название и географически находятся недалеко друг от друга. Поскольку представляют они практически одно и то же, имеет смысл рассматривать их как одну вершину. Необходимо добавить такую возможность

**Comment by HikkMind** [comment]
Явных знаков, которые позволили бы определить схожесть вершин обнаружено не было. Решено использовать расстояние между ними

**Comment by HikkMind** [comment]
Объединение вершин в одну происходит при выполнении следующих условий:
- Вершины имеют одинаковое название
- Вершины ассоциируются с одним видом транспорта
- Находятся на определенном расстоянии друг от друга (по умолчанию 200 метров)

**Comment by HikkMind** [comment]
Добавлен учет фильтрации при объединении вершин. 
- Если вершина не принадлежит ни одному отношению, которое должно входить в граф, она игнорируется и не добавляется в объединение вершин и в граф в целом
- В противном случае объединения вершин связываются, если в обоих есть остановки из одного отношения и они в нем связаны

**Comment by sevryukov** [comment]
@HikkMind на примере этого Issue - какой код связан с этой задачи?
