### ISSUE TITLE
Восстановить отрисовку графа на карте

### ISSUE THREAD

**Issue by HikkMind** [MVjimboUniversity/Urban-Public-Transport-Analysis-Service#152]
При использовании оригинальной библиотеки `osmnx` пропала возможность отрисовки карты общественного транспорта. Необходимо восстановить эту функцию

**Comment by gekkkl** [comment]
Было скорректировано отображение графа на карте, но на карте отображаются вершины и ребра, но не в виде маршрута, а в виде прямых линий между вершинами.

**Comment by gekkkl** [comment]
Была добавлена возможность при нажатии на узел увидеть его характеристики и меры центральности.
