### ISSUE TITLE
Вычислить меры центральности для графа

### ISSUE THREAD

**Issue by HikkMind** [MVjimboUniversity/Urban-Public-Transport-Analysis-Service#154]
Для каждой вершины необходимо вычислить следующие меры центральности:
- _Betweenness_
- _Closeness_
- _PageRank_

**Comment by gekkkl** [comment]
Была реализована мера центральности degree centrality.

**Comment by HikkMind** [comment]
Были реализованы вычисление и отображение таких центральностей как: degree, closeness, betwenness, page rank

**Comment by gekkkl** [comment]
В веб части была реализована возможность выбрать по какой метрике красить вершины при отображении на карте.
