### ISSUE TITLE
Проверить правильность подгружаемых данных для разных видов транспорта

### ISSUE THREAD

**Issue by HikkMind** [MVjimboUniversity/Urban-Public-Transport-Analysis-Service#155]
Нужно проверить подгружаемые данные на соответствие действительности

**Comment by rozotto** [comment]
Помимо автобусов, были проверены трамваи, троллейбусы и метро. Сделан вывод о том, что имеющиеся данные подгружаются верно, однако организация получаемых json-файлов отличается. Из недостатков также имеются:
1. Маршруты без остановок
2. Не весь транспорт города
3. Изолированные вершины
