### ISSUE TITLE
Изучить теорию степенного закона

### ISSUE THREAD

**Issue by HikkMind** [MVjimboUniversity/Urban-Public-Transport-Analysis-Service#159]
Необходимо изучить теорию степенного закона для графов, его содержательность и применимость к поставленной задаче

**Comment by WPeSoul** [comment]
I. Обзор теории законов мощности
Закон мощности, также известный как закон распределения мощности или предсказуемая неравновесность, описывает функциональную зависимость между двумя величинами, при которой относительное изменение одной величины приводит к соответствующему пропорциональному изменению другой величины, не зависящему от начального значения. В двойных логарифмических координатах закон распределения мощности выглядит как прямая линия с отрицательным наклоном. Явления закона мощности широко распространены в природе и социальных системах, таких как размер города, распределение богатства и интернет-трафик, и основаны на идее, что несколько вещей имеют подавляющее большинство ценности, а большинство вещей имеют лишь небольшое количество ценности.

II. значение закона мощности в городском общественном транспорте
1. выявить неравномерность транспортного потока: пассажиропоток в городских системах общественного транспорта, таких как метро и автобусы, как правило, распределяется по закону мощности. Это означает, что на небольшое количество станций или линий приходится большая часть пассажиропотока, в то время как большинство станций или линий имеют относительно низкий трафик. Этот дисбаланс является важным ориентиром при планировании перевозок, расположении станций и распределении пропускной способности.
2. оптимизация распределения ресурсов: с помощью анализа закона мощности можно определить ключевые узлы и узкие места в транспортной системе, чтобы целенаправленно оптимизировать распределение ресурсов. Например, на участках с большим пассажиропотоком можно увеличить количество транспортных средств, повысить частоту обслуживания; на участках с малым пассажиропотоком можно сократить соответствующие инвестиции в пропускную способность, чтобы избежать нерационального использования ресурсов.
3. Повышение эффективности движения: распределение по закону мощности также показывает взаимодействие и влияние между узлами транспортной системы. Благодаря более глубокому пониманию этого механизма взаимодействия можно принять более научные и эффективные меры для повышения операционной эффективности всей транспортной системы и сокращения заторов и задержек.

III. Теории степенного закона применимость к поставленной задаче
1. Выявление дисбаланса в транспортной сети
Распределение по закону мощности может выявить дисбаланс между станциями (узлами) и маршрутами (краями) в транспортной сети. В сложных городских сетях общественного транспорта небольшое количество станций, как правило, обеспечивает большую часть пассажиропотока и маршрутных соединений, в то время как большинство станций являются относительно периферийными, с меньшим пассажиропотоком и маршрутными соединениями. Этот дисбаланс является неотъемлемой чертой городских транспортных сетей, которая может быть эффективно описана и количественно оценена с помощью распределений по закону мощности.
2. Руководство по оптимизации транспортной сети
Изучение распределений по закону мощности в транспортных сетях позволяет выявить критические узлы (т.е. станции с высоким пассажиропотоком и большим количеством маршрутных соединений) и узкие места (т.е. участки маршрутов, которые перегружены и имеют недостаточную пропускную способность). Эта информация очень важна для оптимизации транспортной сети. Например, в ключевые узлы можно направить целевые инвестиции для модернизации их транспортного оборудования и повышения уровня обслуживания; узкие места также можно направить на устранение заторов и расширение пропускной способности для повышения эффективности работы всей транспортной сети.
3. Прогнозирование изменений в спросе на транспортные услуги
Распределение по закону мощности также можно использовать для прогнозирования тенденций изменения спроса на транспорт. С развитием города и миграцией населения пассажиропоток и линии транспортной сети также будут меняться. Сравнивая характеристики распределения по закону мощности в разные периоды времени, можно проанализировать изменение структуры и тенденцию спроса на транспортные услуги, чтобы обеспечить научную основу для будущего планирования и управления движением.
4. Оценка влияния транспортной политики
Распределения по закону мощности также можно использовать для оценки эффективности новой транспортной политики или мер после их внедрения. Например, сравнивая характеристики распределений закона мощности до и после реализации политики, можно проанализировать степень и масштаб воздействия политики на транспортную сеть, а также необходимость дальнейшей корректировки и оптимизации политики.
