### ISSUE TITLE
Реализовать функцию проверки степенного закона 

### ISSUE THREAD

**Issue by HikkMind** [MVjimboUniversity/Urban-Public-Transport-Analysis-Service#160]
Необходимо проверить соблюдается ли степенной закон для строящегося графа

**Comment by WPeSoul** [comment]
## backend/app/power_law_analysis.py
### Файл выполняет следующие задачи:
1. Получение распределения степеней: запрос степени (т.е. количества связей) каждого узла в графе (например, социальной сети, транспортной сети и т.д.) через базу данных Neo4j и преобразование результата в Pandas DataFrame.
2. постройте график распределения степеней: с помощью библиотеки matplotlib постройте график распределения степеней с логарифмической шкалой по горизонтальной оси (степень) и вертикальной оси (частота). Синие точки на графике указывают на данные распределения степеней, которые визуализируют связь между степенью и частотой.
3. подгонка распределения по закону мощности: используйте функцию подгонки распределения по закону мощности библиотеки scipy для подгонки данных распределения по степеням, вывода показателя закона мощности (гамма) и построения графика результатов подгонки. На графике результатов подгонки синие точки указывают на исходные данные, а красная линия - на подогнанную кривую распределения по закону мощности.

### Чтобы определить, соответствует ли распределение степеней закону мощности, можно проделать следующие шаги:
1. Наблюдайте за графиком распределения: если график распределения степеней в логарифмических координатах имеет приблизительно прямолинейную зависимость, это, как правило, характерно для распределения типа «силовой закон».
2. проверка экспоненты силового закона: после подгонки распределения силового закона выходная экспонента силового закона (гамма), если она находится в разумных пределах (обычно больше 0), указывает на то, что данные могут соответствовать распределению силового закона.

## backend/power_law.py
### Файл выполняет следующие задачи:
1. определение функции распределения закона мощности: распределение закона мощности определяется с помощью функции power_law(x, alpha), где x - независимая переменная, а alpha - экспоненциальный параметр распределения закона мощности.
2. plot_distribution и fit_results: функция plot_power_law(values, fit_params) отвечает за построение графика кумулятивной функции распределения (CDF) исходных данных, а также результатов подгонки распределения по закону мощности. Сначала она сортирует данные, а затем вычисляет CDF исходных данных. Затем она генерирует подогнанное распределение по закону мощности и вычисляет его CDF для визуализации.
3. Основная логика:
Используя фреймворк асинхронного программирования asyncio, функция main() сначала запрашивает у пользователя название города.
Используйте различные функции фильтрации в файле network.py для получения заданных данных сети, которые содержат список характеристик узлов.
Извлекаем из списка характеристик значение «center_count» для каждого узла.
Используйте функцию curve_fit для подгонки распределения по закону мощности и получения параметра подгонки alpha.
Вызовите функцию plot_power_law, чтобы построить график CDF исходных данных и результат подгонки распределения по закону мощности.
### Определите, выполняется ли закон мощности:
1. параметр подгонки: проверьте, что значение альфа является разумным. В распределении по закону мощности альфа обычно является положительным числом, и его значение влияет на форму распределения.
2. сравнение графиков: обратите внимание на сходство между CDF исходных данных (синяя кривая) и CDF подогнанного распределения по закону мощности (оранжевая кривая). Если они имеют одинаковую тенденцию и подогнанная кривая хорошо повторяет точки исходных данных, это указывает на то, что данные могут соответствовать распределению по закону мощности.
