### ISSUE TITLE
Построение графа по названию места по запросу 

### ISSUE THREAD

**Issue by MVjimboUniversity** [MVjimboUniversity/Urban-Public-Transport-Analysis-Service#19]
- [x] Реализовать метод, который по названию места возвращает граф дорожно транспортной сети в виде GeoJSON/GeoDataFrame

**Comment by MVjimboUniversity** [comment]
В качестве графа на данном этапе достаточно возвращать граф общественного транспорта

**Comment by SergiusMagnus** [comment]
Метод можно найти по ссылке https://github.com/MVjimboUniversity/Urban-Public-Transport-Analysis-Service/blob/research_graph_creation/research/GraphAsGDF.ipynb

**Comment by MVjimboUniversity** [comment]
Необходимо реализовать метод, который будет обрабатывать запрос на получение графа по названию места. Для примера можно рассмотреть сеть трамвайных путей Санкт-Петербурга. Получить ее можно так
`g = ox.graph_from_place("Санкт-Петербург", network_type= bidirectional_network_types, custom_filter='["railway"~"tram"]')`

**Comment by MVjimboUniversity** [comment]
Возвращать необходимо JSON в формате {"nodes": ... , "edges": ...}. Пример того, как их можно сформировать
```
gdf_nodes, gdf_relationships = ox.graph_to_gdfs(g)
data = {
    "nodes": json.loads(gdf_nodes.to_json()),
    "edges": json.loads(gdf_relationships.to_json()),
}
with open("graph.geojson", "w") as f:
    f.write(json.dumps(data))
```
